#!/usr/bin/env python3
"""attempt.py --corpus <declarations corpus dir> [--only A,B,..] [--sample-mod N]
              [--limit N] [--negate] [--ladder rfl,decide,...] [--heartbeats N]
              [--run-id ID] [--out DIR] [--no-ket] [--timeout S] [--start-timeout S]

Phase-1 attempt driver (ATTEMPTS.md rev 2, scope §3-4). Runs AttemptWalk.lean
under corpus_extract's watchdog/resume machinery, then for every accepted
attempt:
  1. SELF-PROOF GATE (scope §2): the term's used constants may contain neither
     the demonstrandum's name nor any constant whose LOCK equals the
     demonstrandum's lock (locks from the declarations corpus). Recorded as
     `selfproof_ok`; a failure makes the attempt `rejected: self-proof`.
  2. Writes the surviving attempts into a generated module
     calib/Quod/Attempts/<Batch>.lean as
        theorem attempt_i : type_of% <D> := by <tactic>        (or ¬ (type_of% D))
     so the statement re-elaborates from the declaration itself (no pretty-
     print round-trip), and `lake build`s it.
  3. Runs the EXISTING gates unchanged on each attempt declaration:
     axiom_gate.py (via calibrate.axioms / axiom_verdict) and lean4checker
     (via calibrate.CHECKER, same invocation as calibrate.py).
  4. Records one attempt line + ket-puts proof/gate outputs; writes an
     append-only manifest whose CID is the attempt-corpus version.
Verdicts are exactly SEMANTICS.md's proof-verdict lattice; `no_proof_found`
is a distinct outcome tagged with prover + prover_config_cid, never a verdict.
--negate: prover-negative control. ANY accepted+gated ¬T HALTS the run.
"""
import argparse, glob, hashlib, json, os, re, subprocess, sys, time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import corpus_extract as ce   # noqa: E402  (run_segment, normalize, lock_of, sha256_file, ket_put_file)
import calibrate as cal       # noqa: E402  (axioms, axiom_verdict, CHECKER, run, CALIB)

ROOT, CALIB, SCRIPTS = ce.ROOT, ce.CALIB, ce.SCRIPTS
WALKER = os.path.join(SCRIPTS, "AttemptWalk.lean")
ATT_DIR = os.path.join(CALIB, "Quod", "Attempts")


def corpus_locks(corpus_dir: str) -> dict[str, str]:
    locks = {}
    for path in sorted(glob.glob(os.path.join(corpus_dir, "declarations-*.jsonl"))):
        with open(path) as f:
            for line in f:
                r = json.loads(line)
                locks[r["name"]] = r["lock"]
    return locks


def parse_atts(raw_path: str):
    with open(raw_path, errors="replace") as f:
        for line in f:
            if line.startswith("ATT\t"):
                try:
                    yield json.loads(line[4:])
                except json.JSONDecodeError:
                    continue


def selfproof_check(att: dict, locks: dict[str, str]) -> tuple[bool, list[str]]:
    """False iff the proof uses the demonstrandum or any same-lock constant."""
    d = att["demonstrandum"]
    dlock = locks.get(d)
    offenders = [c for c in att.get("used_consts", [])
                 if c == d or (dlock is not None and locks.get(c) == dlock)]
    return (len(offenders) == 0, offenders)


HEADER = """import Mathlib
open Lean Elab Term Meta in
/-- The declaration's statement, read from its ConstantInfo (no pretty-print
round-trip), with universe params instantiated as u_0.. — the theorem using
it declares matching universe binders. -/
elab "type_of_decl! " n:ident : term => do
  let ci ← getConstInfo n.getId
  let us := (List.range ci.levelParams.length).map fun i => mkLevelParam (Name.mkSimple s!"u_{i}")
  return ci.type.instantiateLevelParams ci.levelParams us

-- generated by scripts/attempt.py; one theorem per accepted attempt
set_option maxHeartbeats 400000
"""


def write_batch_module(batch: str, atts: list[dict], negate: bool) -> str:
    """Generate calib/Quod/Attempts/<batch>.lean; returns the module name."""
    os.makedirs(ATT_DIR, exist_ok=True)
    lines = [HEADER]
    for a in atts:
        n = int(a.get("n_levels", 0))
        univ = ".{" + ",".join(f"u_{i}" for i in range(n)) + "}" if n else ""
        body = f"type_of_decl! {a['demonstrandum']}"
        stmt = f"¬ ({body})" if negate else body
        lines.append(f"theorem {a['attempt_name']}{univ} : {stmt} := by {a['tactic']}")
        lines.append("")
    with open(os.path.join(ATT_DIR, f"{batch}.lean"), "w") as f:
        f.write("\n".join(lines))
    return f"Quod.Attempts.{batch}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--only", default="")
    ap.add_argument("--sample-mod", type=int, default=1)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--negate", action="store_true")
    ap.add_argument("--ladder", default="rfl,decide,simp,omega,exact?,aesop")
    ap.add_argument("--heartbeats", type=int, default=20_000_000)
    ap.add_argument("--run-id", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--timeout", type=int, default=60, help="per-demonstrandum wall-clock watchdog (decision 3)")
    ap.add_argument("--start-timeout", type=int, default=900)
    ap.add_argument("--no-ket", action="store_true")
    args = ap.parse_args()

    run_id = args.run_id or time.strftime("attempts-%Y%m%d-%H%M%S")
    out_dir = args.out or os.path.join(ROOT, "attempts", run_id)
    os.makedirs(out_dir, exist_ok=True)
    raw, err = os.path.join(out_dir, "records.raw"), os.path.join(out_dir, "walker.err")
    prover = "ladder-A"
    prover_config = {"prover": prover, "ladder": args.ladder.split(","), "heartbeats_per_rung": args.heartbeats,
                     "wall_s_per_demonstrandum": args.timeout, "negate": args.negate,
                     "walker_sha256": ce.sha256_file(WALKER)}
    def put_bytes(b: bytes, name: str):
        if args.no_ket:
            return None
        p = os.path.join(out_dir, f".{name}.tmp")
        with open(p, "wb") as f:
            f.write(b)
        try:
            return ce.ket_put_file(p)
        finally:
            os.unlink(p)
    prover_config_cid = put_bytes(json.dumps(prover_config, sort_keys=True).encode(), "prover_config")

    ce.WALKER = WALKER
    env = {"CORPUS_SAMPLE_MOD": str(args.sample_mod), "ATTEMPT_LADDER": args.ladder,
           "ATTEMPT_HEARTBEATS": str(args.heartbeats)}
    if args.only:
        env["CORPUS_ONLY"] = args.only
    if args.limit:
        env["CORPUS_LIMIT"] = str(args.limit)
    if args.negate:
        env["CORPUS_NEGATE"] = "1"
    resume, skips, no_progress, t0 = "", [], 0, time.time()
    while True:
        before = os.path.getsize(raw) if os.path.exists(raw) else 0
        seg = dict(env)
        if resume:
            seg["CORPUS_RESUME_AFTER"] = resume
        status, hung = ce.run_segment(seg, raw, err, inactivity=args.timeout, startup=args.start_timeout)
        print(f"attempt: segment {status} (hung={hung})", file=sys.stderr)
        if status == "done":
            break
        after = os.path.getsize(raw) if os.path.exists(raw) else 0
        no_progress = no_progress + 1 if after == before else 0
        if no_progress >= 5 or hung is None:
            sys.exit(f"attempt: no progress ({status}, hung={hung}); aborting")
        skips.append({"name": hung, "status": status, "outcome": "no_proof_found", "reason": "wall-clock watchdog"})
        resume = hung

    locks = corpus_locks(args.corpus)
    atts = list(parse_atts(raw))
    accepted = []
    for i, a in enumerate(atts):
        a["prover"], a["prover_config_cid"] = prover, prover_config_cid
        if a["outcome"] != "accepted":
            continue
        ok, offenders = selfproof_check(a, locks)
        a["selfproof_ok"], a["selfproof_offenders"] = ok, offenders
        if not ok:
            a["verdict"] = "rejected: self-proof"
            continue
        a["attempt_name"] = f"attempt_{i}"
        accepted.append(a)

    # external gates on a generated module (gates run exactly as calibrate.py runs them)
    if accepted:
        batch = "B" + re.sub(r"[^0-9A-Za-z]", "", run_id)
        module = write_batch_module(batch, accepted, args.negate)
        brc, bout = cal.run(["lake", "build", module], cwd=CALIB)
        build_ok = brc == 0
        for a in accepted:
            if not build_ok:
                a["verdict"] = "rejected: batch build failed"
                a["build_err"] = bout[-400:]
                continue
            _, ax, raw_ax = cal.axioms(CALIB, module, a["attempt_name"])
            a["gate_axioms"] = ax.get("axioms")
            a["verdict"] = cal.axiom_verdict(ax)
            a["axioms_cid"] = put_bytes(raw_ax.encode(), f"ax_{a['attempt_name']}")
        if build_ok and any(a["verdict"] == "accepted" for a in accepted):
            krc, kout = cal.run(["lake", "env", cal.CHECKER, module], cwd=CALIB)
            kcid = put_bytes(kout.encode(), "checker")
            for a in accepted:
                if a["verdict"] == "accepted":
                    a["checker_rc"], a["checker_cid"] = krc, kcid
                    if krc != 0:
                        a["verdict"] = "rejected: lean4checker"

    # prover-negative halt: an accepted, fully gated ¬T means the pin is inconsistent
    if args.negate:
        bad = [a["demonstrandum"] for a in accepted if a.get("verdict") == "accepted"]
        if bad:
            sys.exit(f"HALT: {len(bad)} negated demonstranda ACCEPTED through all gates — pin inconsistent or "
                     f"harness bug: {bad[:5]}")

    # write the attempt corpus
    path = os.path.join(out_dir, "attempts.jsonl")
    n_by = {}
    with open(path, "w") as f:
        for a in atts + [{"demonstrandum": s["name"], "outcome": "no_proof_found", "prover": prover,
                          "prover_config_cid": prover_config_cid, "negated": args.negate,
                          "watchdog": True} for s in skips]:
            a.setdefault("verdict", None)
            key = a.get("verdict") or a["outcome"]
            n_by[key] = n_by.get(key, 0) + 1
            f.write(json.dumps(a, ensure_ascii=False) + "\n")
    manifest = {"run_id": run_id, "prover": prover, "prover_config": prover_config,
                "prover_config_cid": prover_config_cid, "negate": args.negate,
                "elapsed_s": round(time.time() - t0, 1), "attempts": len(atts) + len(skips),
                "by_outcome": n_by, "watchdog_skips": len(skips),
                "scripts": {f: ce.sha256_file(os.path.join(SCRIPTS, f)) for f in sorted(os.listdir(SCRIPTS))
                            if f.endswith((".py", ".lean", ".sh"))},
                "attempts_sha256": ce.sha256_file(path)}
    if not args.no_ket:
        manifest["attempts_cid"] = ce.ket_put_file(path)
    man = os.path.join(out_dir, f"manifest-{run_id}.json")
    with open(man, "w") as f:
        json.dump(manifest, f, indent=1)
    if not args.no_ket:
        print(f"manifest CID: {ce.ket_put_file(man)}")
    print(f"attempts: {len(atts) + len(skips)} | {n_by} -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
